version: '3.3'

services:

   node:
     image: node:8
     build: .
     restart: always
     volumes:
       - ./app:/usr/src/app

   web:
     image: nginx
     depends_on:
       - node
     restart: always
     volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - ./logs:/var/log/nginx

   https-portal:
     image: steveltn/https-portal:1
     depends_on:
       - web
     ports:
       - 80:80
       - 443:443
     restart: always

     volumes:
       - ./ssl_certs:/var/lib/https-portal
     environment:
       DOMAINS: 'node.localhost -> http://web:80 #local'
